# Generated by Django 6.0.6 on 2026-07-06 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('avaliacao', models.IntegerField()),
                ('image', models.ImageField(upload_to='uploads/')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'verbose_name': 'Escola',
                'verbose_name_plural': 'Escolas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('imagem', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Motd',
            fields=[
                ('motd', models.CharField(db_column='MOTD', max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Mensagem do Dia',
                'verbose_name_plural': 'Mensagens do Dia',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('escola', models.ForeignKey(db_column='id_escola', on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='core.escola')),
            ],
            options={
                'ordering': ['-data_hora'],
            },
        ),
    ]
