# Generated by Django 6.0.6 on 2026-07-06 16:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('avaliacao', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('image', models.ImageField(upload_to='uploads/')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'verbose_name': 'Escola',
                'verbose_name_plural': 'Escolas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Motd',
            fields=[
                ('motd', models.CharField(db_column='MOTD', max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Mensagem do Dia',
                'verbose_name_plural': 'Mensagens do Dia',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL)),
                ('resposta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='core.comentario')),
                ('escola', models.ForeignKey(db_column='id_escola', on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='core.escola')),
            ],
            options={
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('imagem', models.ImageField(upload_to='prints/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Imagem (print) associada a um usuário',
                'verbose_name_plural': 'Imagem (print) associada a um usuário',
            },
        ),
        migrations.CreateModel(
            name='Reacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reacao', models.CharField(choices=[('like', 'Like'), ('fav', 'Favorito')], max_length=10)),
                ('data_hora_reacao', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comentario', models.ForeignKey(db_column='id_comentario', on_delete=django.db.models.deletion.CASCADE, related_name='reacoes', to='core.comentario')),
            ],
        ),
    ]
