# Generated by Django 6.0.6 on 2026-07-06 14:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escola',
            name='avaliacao',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
